version: 0.2

batch:
  fast-fail: false
  build-matrix:
    static:
      ignore-failure: false
      env:
        variables:
          STATIC_VAR: 'This is the static variable'

    dynamic:
      buildspec: 
        - matrix1.yml
        - matrix2.yml
      env:
        variables:
          MY_VAR:
            - VALUE1
            - VALUE2
            - VALUE3

env:
  variables:
    GLOBAL_VAR: 'This is the global variable'
